// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egapzxoadkwfganylxql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnYXB6eG9hZGt3ZmdhbnlseHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjAyNTQsImV4cCI6MjA2MTgzNjI1NH0.6HYN7CuS8N3i_OPtru2aJ7Uar0WUgWORK_W3ixVttB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);